services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres
    hostname: postgres
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - ./drives/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - trino-network
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"


  hive-metastore:
    image: 'my-hive-metastore:latest'
    container_name: metastore
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ../common_conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
#      - ./drives/metastore_opt:/opt
    environment:
      METASTORE_DB_HOSTNAME: postgres
      METASTORE_TYPE: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - trino-network

  minio:
    image: 'minio/minio:latest'
    container_name: minio
    hostname: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data_1:/data1
      - minio_data_2:/data2

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data1 /data2
    networks:
      - trino-network

networks:
  trino-network:
    driver: bridge

volumes:
  minio_data_1:
  minio_data_2:
